package com.rollbackshield.audit;

public enum AuditAction {
    RELEASE_CREATED,
    RELEASE_STATE_CHANGED,
    CONTRACT_CREATED,
    CONTRACT_ACTIVATED,
    MUTATION_ALLOWED,
    MUTATION_BLOCKED,
    WORK_ENQUEUED,
    WORK_EXECUTED,
    EPOCH_INVALIDATED,
    WORK_CANCELLED,
    ROLLBACK_REQUESTED,
    ROLLBACK_COMPLETED,
    COMMIT_REQUESTED,
    COMMIT_COMPLETED,
    STATE_TRANSITION_FAILED
}
